//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZMALAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class instytucja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public instytucja()
        {
            this.uzytkowniks = new HashSet<uzytkownik>();
        }
    
        public int id_instytucji { get; set; }
        public string adres { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string nazwa_instytucji { get; set; }
        public Nullable<double> szerokosc { get; set; }
        public Nullable<double> dlugosc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uzytkownik> uzytkowniks { get; set; }
    }
}
