//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZMALAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zgloszenie
    {
        public int id_zgloszenia { get; set; }
        public string typ_zgloszenia { get; set; }
        public string adres { get; set; }
        public Nullable<int> status { get; set; }
        public string fk_login { get; set; }
        public string szerokosc { get; set; }
        public string dlugosc { get; set; }
        public string opis { get; set; }
        public System.DateTime data_rozpoczecia { get; set; }
        public System.DateTime data_zakonczenia { get; set; }
        public string nazwa_zgloszenia { get; set; }
        public string image { get; set; }
    
        public virtual uzytkownik uzytkownik { get; set; }
    }
}
